### ISSUE TITLE
Create dataset

### ISSUE THREAD

**Issue by sowmyay** [sowmyay/w4c#2]
**Competition data** 

Name | Folder | Variables | Target Variable | type | Range | Scale Factor | Offset
:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|
Temperature at Ground/Cloud | CTTH |  `temperature` <br /> `ctth_tempe` <br /> `ctth_pres` <br /> `ctth_alti` <br /> `ctth_effectiv` `ctth_method` <br /> `ctth_quality` <br /> `ishai_skt` <br /> `ishai_quality` | `temperature` | uint16 | 0-11000 | 10 | 0
Convective Rainfall Rate | CRR | `crr` <br /> `crr_intensity` <br /> `crr_accum` <br /> `crr_quality` | `crr_intensity` | uint16 | 0-500 | 0.1 | 0
Probability of Occurrence of Tropopause Folding | ASII | `asii_turb_trop_prob` <br /> `asiitf_quality` | `asii_turb_trop_prob` | uint8 | 0-100 | 1 | 0
Cloud Mask | CMA | `cma_cloudsnow` <br /> `cma` <br /> `cma_dust` <br /> `cma_volcanic` <br /> `cma_smoke` <br /> `cma_quality` | `cma` | uint8 | 0-1 | 1 | 0
Cloud Type | CT | `ct` <br /> `ct_cumuliform` <br /> `ct_multilayer` <br /> `ct_quality` | `None` | uint8 | `None` | `None` | `None`

**Discussion** 

1. Temperature: Given 9 layers, predict 1: `temperature`
2. CRR: Given 4 layers, predict 1: `crr_intensity`
3. Tropopause probability: Given 2 layers, predict 1: `asii_turb_trop_prob`
4. Cloud mask: Given 6 layers, predict 1: `cma`
5. Cloud type: Given 4 layers

Total input layers : 25 (9 + 4 + 2 + 6 + 4)
Total output layers : 4

Number of input timestamps: 4
Number of target timestamps: 32

=> Input :  `4x25x256x256`
=> Target: `32x4x256x256`

**Open Questions**

1. In each day, we have 24 x (60/15) = 96 files (15 mins granularity). Let us represent them as `0, 1, 2, 3, 4....31, 32.....95`. When we create (input, target) tuples, how should we slice the hours? If the slice is - input as [0, 1, 2, 3] and target as [4, 5, 6.....31], then the net slice as -
- [ ] next input as [32, 33, 34, 35], next target as [36, ...67] and so on? If we do this, how do we ensure that we don't end up training on the same hours across multiple days. I.e, 0 to 4 hours, are always in the input, and never in the target. Otherwise, we end up always training on these hours but never predicting.
- [ ] next input as [1, 2, 3, 4], next target as [5, 6, ....32] and so on? Might there be any data leak in this case?

2. Preprocessed training pairs
- [ ] Should we create preprocessed training pairs (input, target) and save them to disk, like it was done in `sensr`?
- [ ] Or can we simply create them during the data loading step?

**TODO**
- [ ] Ability to read the competition
- [ ] Preprocess layers
- [ ] Patch layers
- [ ] Generate (input, target) pairs
